### ISSUE TITLE
Not reactive...

### ISSUE THREAD

**Issue by jfklimek** [zachcmathews/teletype-revit-linker#3]
I've tried installing this in Revit 2019 and 2020 and neither of them are showing me anything. I'm new to github and am not sure where to write this comment so i'm just putting it here hoping I can find some guidance how to install this into my Revit. I'm using Atom Teletype (awesome)! and Teletype Revit Linker and extracted the KeynotesRTC to the add-in folder as explained. Any help would be appreciated. Also, is the intention to update this for 2021 as well... and beyond? I like this Keynote revit workflow very much!

**Comment by zachcmathews** [comment]
Please refer to [https://github.com/zachcmathews/LTFilter/issues/2](https://github.com/zachcmathews/LTFilter/issues/2) for the solution to this issue.

My intention is to keep it updated as long as Revit continues to use tab-delimited files for keynotes provided that [the API](https://www.revitapidocs.com/2019/62f3d036-0094-2f78-45ed-7815dd95565f.htm) remains open. I see no reason this shouldn't work for 2021 as of now, but the API docs only go to 2020, so I could be wrong.
